spring:
  application:
    name: component-detail-service
  r2dbc:
    url: ${URL}
    username: ${USER_NAME}
    password: ${PASSWORD}
server:
  port: 8090

external-services:
  component-service:
    url: "${component-service-url:http://localhost:8080/component/api/v1}"